# permissions for end users to edit controllermanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllermanagerconfig-editor-role
rules:
- apiGroups:
  - config.tbnco.github.io
  resources:
  - controllermanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.tbnco.github.io
  resources:
  - controllermanagerconfigs/status
  verbs:
  - get
