# permissions for end users to view controllermanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllermanagerconfig-viewer-role
rules:
- apiGroups:
  - config.tbnco.github.io
  resources:
  - controllermanagerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.tbnco.github.io
  resources:
  - controllermanagerconfigs/status
  verbs:
  - get
