apiVersion: config.tbnco.github.io/v1alpha1
kind: ControllerManagerConfig
spec:
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: 5b2736bb.tbnco.github.io
  # Select namespaces for processing.
  namespaceSelector:
    matchExpressions:
      # Example how to exclude namespaces.
      - key: tbnco.github.io/environment
        operator: NotIn
        values:
          - dev
